apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: neptune-blog
      name: api-gateway-pod
  template:
    metadata:
      labels:
        app: neptune-blog
        name: api-gateway-pod
    spec:
      containers:
        - name: api-gateway
          image: registry.cn-shenzhen.aliyuncs.com/neptune-blog/api-gateway:1.0
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: EUREKA_SERVER_ADDRESSES
              valueFrom:
                configMapKeyRef:
                  name: neptune-blog-config-map
                  key: eureka_service_addresses
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
      imagePullSecrets:
        - name: aliyun-shenzhen
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
  labels:
    app: neptune-blog
    name: api-gateway-service
spec:
  type: NodePort
  selector:
    app: neptune-blog
    name: api-gateway-pod
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31080