apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: neptune-blog
      name: config-server-pod
  template:
    metadata:
      labels:
        app: neptune-blog
        name: config-server-pod
    spec:
      containers:
        - name: config-server
          image: registry.cn-shenzhen.aliyuncs.com/neptune-blog/config-server:1.0
          ports:
            - containerPort: 8090
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: EUREKA_SERVER_ADDRESSES
              valueFrom:
                configMapKeyRef:
                  name: neptune-blog-config-map
                  key: eureka_service_addresses
          livenessProbe:
            httpGet:
              path: /
              port: 8090
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 8090
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
      imagePullSecrets:
        - name: aliyun-shenzhen