apiVersion: apps/v1
kind: Deployment
metadata:
  name: tweet-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: neptune-blog
      name: tweet-pod
  template:
    metadata:
      labels:
        app: neptune-blog
        name: tweet-pod
    spec:
      containers:
        - name: tweet-server
          image: registry.cn-shenzhen.aliyuncs.com/neptune-blog/tweet-server:1.0
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: EUREKA_SERVER_ADDRESSES
              valueFrom:
                configMapKeyRef:
                  name: neptune-blog-config-map
                  key: eureka_service_addresses
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
      imagePullSecrets:
        - name: aliyun-shenzhen