apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  labels:
    app: neptune-blog
    name: mysql-pod
    tier: middleware
spec:
  containers:
    - name: mysql
      image: mysql:8.0.21
      ports:
        - containerPort: 3306
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: "12345678"
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels:
    app: neptune-blog
    tier: middleware
spec:
  type: NodePort
  ports:
    - port: 3306
      targetPort: 3306
      nodePort: 30201
  selector:
    app: neptune-blog
    name: mysql-pod
---
apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
  labels:
    app: neptune-blog
    name: redis-pod
    tier: middleware
spec:
  containers:
    - name: redis
      image: redis:6.0.8
      ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels:
    app: neptune-blog
    tier: middleware
spec:
  type: NodePort
  ports:
    - port: 6379
      targetPort: 6379
      nodePort: 30202
  selector:
    app: neptune-blog
    name: redis-pod
---
apiVersion: v1
kind: Pod
metadata:
  name: rabbitmq-pod
  labels:
    app: neptune-blog
    name: rabbitmq-pod
    tier: middleware
spec:
  containers:
    - name: rabbitmq
      image: rabbitmq:3.8.9-management-alpine
      ports:
        - containerPort: 5672
        - containerPort: 15672
      env:
        - name: RABBITMQ_DEFAULT_USER
          value: root
        - name: RABBITMQ_DEFAULT_PASS
          value: "12345678"
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
  labels:
    app: neptune-blog
    tier: middleware
spec:
  type: NodePort
  ports:
    - name: server
      port: 5672
      targetPort: 5672
      nodePort: 30203
    - name: management
      port: 15672
      targetPort: 15672
      nodePort: 30204
  selector:
    app: neptune-blog
    name: rabbitmq-pod
---
apiVersion: v1
kind: Pod
metadata:
  name: minio-pod
  labels:
    app: neptune-blog
    name: minio-pod
    tier: middleware
spec:
  containers:
    - name: minio
      image: minio/minio:RELEASE.2020-08-27T05-16-20Z
      ports:
        - containerPort: 9000
      env:
        - name: MINIO_ACCESS_KEY
          value: root
        - name: MINIO_SECRET_KEY
          value: "12345678"
      command: [ "minio" ]
      args: [ "server", "/data" ]
---
apiVersion: v1
kind: Service
metadata:
  name: minio-service
  labels:
    app: neptune-blog
    tier: middleware
spec:
  type: NodePort
  ports:
    - port: 9000
      targetPort: 9000
      nodePort: 30205
  selector:
    app: neptune-blog
    name: minio-pod
---
apiVersion: v1
kind: Pod
metadata:
  name: zipkin-pod
  labels:
    app: neptune-blog
    name: zipkin-pod
    tier: middleware
spec:
  containers:
    - name: zipkin
      image: openzipkin/zipkin:2.21.7
      ports:
        - containerPort: 9411
---
apiVersion: v1
kind: Service
metadata:
  name: zipkin-service
  labels:
    app: neptune-blog
    tier: middleware
spec:
  type: NodePort
  ports:
    - port: 9411
      targetPort: 9411
      nodePort: 30206
  selector:
    app: neptune-blog
    name: zipkin-pod