server:
  port: 8090
spring:
  rabbitmq:
    host: rabbitmq-service
    port: 5672
    username: root
    password: 12345678
    virtual-host: /
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_ADDRESSES}
  instance:
    preferIpAddress: true
