server:
  port: 8090
spring:
  rabbitmq:
    host: ${SERVER_HOST}
    port: 5672
    username: scott
    password: 12345678
    virtual-host: /
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_ADDRESSES}
  instance:
    preferIpAddress: true
