server:
  port: 8090
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: root
    password: 12345678
    virtual-host: /
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
